---
- hosts: all
  gather_facts: false
  
  vars:
    ansible_connection: ansible.netcommon.network_cli
    ansible_user: netadmin
    ansible_password: s3cr3tpw1

  tasks:

  - name: Gather all IOS Facts
    cisco.ios.ios_facts:
      gather_network_resources:
      - interfaces
      - vlans
      - l3_interfaces
      - l2_interfaces
      - hostname
    when: ansible_network_os == "ios"
    register: iosxe_device_facts
  
  - name: Gather all NXOS facts
    cisco.nxos.nxos_facts:
      gather_network_resources:
      - interfaces
      - vlans
      - l3_interfaces
      - l2_interfaces
      - hostname
    when: ansible_network_os == "nxos"
    register: nxos_device_facts

  - name: Print output to file
    ansible.builtin.copy:
      content: "{{iosxe_device_facts | to_json(indent=4, sort_keys=True)  }}"
      dest: ./raw_data/{{inventory_hostname}}.json
    when: iosxe_device_facts.ansible_facts is defined

  - name: Print output to file
    ansible.builtin.copy:
      content: "{{nxos_device_facts | to_json(indent=4, sort_keys=True)  }}"
      dest: ./raw_data/{{inventory_hostname}}.json
    when: nxos_device_facts.ansible_facts is defined
